sudo: false
language: python
python:
  - "3.5"
dist: trusty
env:
  global:
    - PYTEST_ADDOPTS="-n 2 --durations 50"
  matrix:
    # byzantium goes first because it takes the longest.
    - TOX_POSARGS="-e py35-native-state-byzantium"
    - TOX_POSARGS="-e py35-rpc-state-byzantium"
    - TOX_POSARGS="-e py35-native-state-frontier"
    - TOX_POSARGS="-e py35-rpc-state-frontier"
    - TOX_POSARGS="-e py35-native-state-homestead"
    - TOX_POSARGS="-e py35-rpc-state-homestead"
    - TOX_POSARGS="-e py35-native-state-eip150"
    - TOX_POSARGS="-e py35-rpc-state-eip150"
    - TOX_POSARGS="-e py35-native-state-eip158"
    - TOX_POSARGS="-e py35-rpc-state-eip158"
    #- TOX_POSARGS="-e py35-native-state-constantinople"
    #- TOX_POSARGS="-e py35-native-state-metropolis"
    - TOX_POSARGS="-e py35-native-blockchain"
    - TOX_POSARGS="-e py35-rpc-blockchain"
    - TOX_POSARGS="-e py35-vm"
    - TOX_POSARGS="-e py35-core"
    - TOX_POSARGS="-e py35-transactions"
    - TOX_POSARGS="-e py35-p2p"
    - TOX_POSARGS="-e py35-database"
    - TOX_POSARGS="-e py35-rpc-state-quadratic"
    #- TOX_POSARGS="-e py35-vm-performance"
    - TOX_POSARGS="-e flake8"
    - TOX_POSARGS="-e mypy"
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - pip freeze
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
