sudo: false
language: python
dist: trusty
env:
  global:
    - PYTEST_ADDOPTS="-n 2 --durations 50"
matrix:
  include:
    #
    # Linting and Static Analysis
    #
    - python: "3.5"
      env: TOX_POSARGS="-e flake8"
    - python: "3.5"
      env: TOX_POSARGS="-e mypy"
    #
    # Python 3.5
    #
    - python: "3.5"
      env: TOX_POSARGS="-e py35-native-state-byzantium"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-rpc-state-byzantium"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-native-state-frontier"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-rpc-state-frontier"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-native-state-homestead"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-rpc-state-homestead"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-native-state-eip150"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-rpc-state-eip150"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-native-state-eip158"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-rpc-state-eip158"
    #- python: "3.5"
    #- env: TOX_POSARGS="-e py35-native-state-constantinople"
    #- python: "3.5"
    #- env: TOX_POSARGS="-e py35-native-state-metropolis"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-native-blockchain"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-rpc-blockchain"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-vm"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-transactions"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-p2p"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-database"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-rpc-state-quadratic"
    #- python: "3.5"
    #- env: TOX_POSARGS="-e py35-vm-performance"
    #
    # Python 3.6
    #
    - python: "3.6"
      env: TOX_POSARGS="-e py36-native-state-byzantium"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-rpc-state-byzantium"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-native-state-frontier"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-rpc-state-frontier"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-native-state-homestead"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-rpc-state-homestead"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-native-state-eip150"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-rpc-state-eip150"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-native-state-eip158"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-rpc-state-eip158"
    #- python: "3.6"
    #- env: TOX_POSARGS="-e py36-native-state-constantinople"
    #- python: "3.6"
    #- env: TOX_POSARGS="-e py36-native-state-metropolis"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-native-blockchain"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-rpc-blockchain"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-vm"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-core"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-transactions"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-p2p"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-database"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-rpc-state-quadratic"
    #- python: "3.6"
    #- env: TOX_POSARGS="-e py36-vm-performance"
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - pip freeze
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
