blank_issues_enabled: true
contact_links:
  - name: Questions about using py-evm?
    url: https://discord.gg/GHryRvPB84
    about: You can ask and answer usage questions on the Ethereum Python Community Discord
